### ISSUE TITLE
Dark variant does not work in SvelteKit

### ISSUE THREAD

**Issue by Bluskript** [windicss/vite-plugin-windicss#172]
**Describe the bug**
When trying to use `dark:` variants with SvelteKit, no styling is outputted.

It is worth mentioning that other variants output CSS that works fine (e.g. sm/md/lg/xl).

**Minimal Reproductions**
https://github.com/Bluskript/portfolio/tree/1a7b9381972284e59cc30a9de0fdc068b59683f7

**Versions**
- vite-plugin-windicss: 0.15.10
- vite: ^2.3.1
- framework(vue/react/svelte/etc): sveltejs/kit@next

**Comment by Bluskript** [comment]
New findings:

- Dark variants work when styled inline in a component
- Creating an element in the component with `class="dark"` does not make the variant work, meaning it's not Svelte's CSS optimization
- Dark mode works when using `darkMode: 'media'`

**Comment by alexanderniebuhr** [comment]
more insights posted in [discord](https://ptb.discord.com/channels/810981250981953597/819462973029351425/843909034579198022).. copied main information below

**input style block**
```svelte
<style lang="postcss" global>
  :local(button) {
    @apply dark:bg-blue-700;
  }
</style>
```
**turns in two steps into**
```svelte
<style global>
  .dark :local(button) {
    --tw-bg-opacity: 1;
    background-color(1,2,3,var(--tw-bg-opacity)); /* whatever the color is */
  }
</style>
```
```svelte
<style>
  :global(.dark) button {
    --tw-bg-opacity: 1;
    background-color(1,2,3,var(--tw-bg-opacity)); /* whatever the color is */
  }
</style>
```

**Comment by alexanderniebuhr** [comment]
quick update to keep this issue with all information up to date.
after some more findings in discord see [svelte channel](https://discord.com/channels/810981250981953597/819462973029351425/843841313602535424)

I think this is caused by svelte removing unused css styles, not used in markup. The reason why dark get's removed is available in the discord discussion. However it seems the warning that styles get removed is missing, it seems [in this](https://discord.com/channels/810981250981953597/819462973029351425/843947593884368948).

To handle that issue, styles would need to be wrapped in .svelte files with `:global()`, which is complex for `@apply' the sibling issue in svelte-windicss-preprocess above. 

There are also some workarounds to this, shown in the discord ([external css file](https://discord.com/channels/810981250981953597/819462973029351425/843927290685161523), [dark class by default](https://discord.com/channels/810981250981953597/819462973029351425/843846093288767502))

**Comment by alexanderniebuhr** [comment]
@antfu which upstream bug are you referring to?

**Comment by antfu** [comment]
From my understanding, this isn't working because Svelte think it's not used and removed it? If so, I'd think it's out-of-scope of the vite plugin.

**Comment by alexanderniebuhr** [comment]
Yes you are right, svelte does remove unused CSS rules. However that is not seen as a bug in svelte, I actually think it is the expected behavior.

There are many solutions for this problem, with the global css rules in svelte being the most useful I guess, I agree with you that it is out-of-scope to hack the removing part of svelte, but at least improving the experience with workarounds was my goal in **svelte-windicss-preprocess**

However it seems that **vite-plugin-windicss** does not include `<style global>` syntax (which is expected since it is svelte specific, and can be implemented with [svelte-preprocess](https://github.com/sveltejs/svelte-preprocess) ), most people will likely use `:global()` syntax as an alternative in their `<style>` blocks (like below).. 

I am not sure how **vite-plugin-windicss** handles the input code ( i have not tested that in the plugin, so it might not be the same error I am talking about .. if so forgive me) , but I can give you insights how it broke for **svelte-windicss-preprocess**.
_To note using only media based queries `lg:` will not have this problem, since they wrap css rule, either non-global or global._

input code
```svelte
<style>
  :global(a) {
    @apply text-black hover:text-emerald-400;
  }
  :global(div) {
    @apply bg-light-800 dark:bg-dark-600;
  }
</style>
```

wrong behavior in **svelte-windicss-preprocess** before [fix reference](https://github.com/windicss/svelte-windicss-preprocess/commit/1ce7d7742f3c267d041a26d20aaa5c0ac9222633
)
```svelte
<style>
:global(a) {
  --tw-text-opacity: 1;
  color: rgba(0, 0, 0, var(--tw-text-opacity));
}
:global(a):hover {
  --tw-text-opacity: 1;
  color: rgba(52, 211, 153, var(--tw-text-opacity));
}
:global(div) {
  --tw-bg-opacity: 1;
  background-color: rgba(222, 226, 230, var(--tw-bg-opacity));
}
.dark :global(div) {
  --tw-bg-opacity: 1;
  background-color: rgba(28, 28, 30, var(--tw-bg-opacity));
}
</style>
```

expected behavior with output code, which can be compiled with svelte to global
```svelte
<style>
:global(a) {
  --tw-text-opacity: 1;
  color: rgba(0, 0, 0, var(--tw-text-opacity));
}
:global(a:hover) {
  --tw-text-opacity: 1;
  color: rgba(52, 211, 153, var(--tw-text-opacity));
}
:global(div) {
  --tw-bg-opacity: 1;
  background-color: rgba(222, 226, 230, var(--tw-bg-opacity));
}
:global(.dark div) {
  --tw-bg-opacity: 1;
  background-color: rgba(28, 28, 30, var(--tw-bg-opacity));
}
</style>
```

**Comment by antfu** [comment]
Does Svelte somehow have a configure to disable this behavior? Not a Svelte user but this does confused me a bit. Another aspect of this might be just moving the style into a real css since it's already expected to be global?

**Comment by alexanderniebuhr** [comment]
no way I am aware of. The way to tell svelte not to remove styles is to declare them as global.. svelte has scoped css first. 
This generally works fine because you can wrap css rule selector in `:global()`, but with windi css and it's `@apply` syntax you can effectly write one css rule in your style block and it get's interpreted into more css rule selectors.

Indeed using a css file would work, i guess. There are many workarounds, also listed above, but it seems that the OP want's to use this syntax. (which I can understand, because declaring them all seperatly cuts away major selling point of windi css)

Another thing to consider is, that SvelteKit is still not stable released yet, so there might be changes to the way `:global()` works. But knowing that in it's base `svelte` it is the same issue, I do not expect that to change.

---
for example:
this should work with no problem, since you manually define the rule selector, wrap them with global and windicss does not interpret the `@apply` part into multiple css rules.

```svelte
<style>
  :global(a) {
    @apply text-black
  }
  :global(a:hover) {
    @apply bg-green;
  }
</style>
```

however this will not work since you only define the one rule selector. Since having `hover:`  in the `@apply` windi will have to interpret another css rule with `a:hover`. However Windi does not know `:global()` and **vite-plugin-windicss** does not handle it, as far as I can tell, so it messes it up shown in the code snippets above

```svelte
<style>
  :global(a) {
    @apply text-black hover:bg-green;
  }
</style>
```
