### ISSUE TITLE
Svelte Windi Compilation issues

### ISSUE THREAD

**Issue by Taha-Firoz** [windicss/vite-plugin-windicss#78]
#### 1. Conditionally applied classes within class aren't detected by windi
`<span class="{foo?"bg-blue-500":"bg-red-600"}"></span>`
Here Windi will not consider `bg-blue-500` or `bg-red-600` in it's compiled css, whether this is  the  best or worst way to implement such a  feature is  a debate for another day but the easiest fix I have is to make a hidden component and shove these classes in it.

#### 2. `@apply hover:bg-red-300` in a svelte files style tag fails to compile
There's a compilation  error when there's a `:` in an `@apply` statement. I moved the definition to the `style.css` file and everything compiled and worked as normal.

**Comment by antfu** [comment]
1. This should be included. Can you share are minimal repo?

2. Might be related to #54

/cc @dominikg do you have any idea on this?

**Comment by Taha-Firoz** [comment]
I mean 2. would refuse to compile at all not just emit something broken

**Comment by antfu** [comment]
Then please keep track in #54, thanks.

**Comment by dominikg** [comment]
> `<span class="{foo?"bg-blue-500":"bg-red-600"}"></span>`

would be better like this `<span class:bg-blue-500={foo} class:bg-blue-600={!foo}></span>` because it would be easier for an extractor to look for class:XXXX=  than to try and tokenize anything inside class={YYYYY}.

In the end all dynamic uses of generated classes pose a risk though because extracting them is harder and they might end up staying unused at runtime. So if you can, think about how you can solve this styling in a consistent way without using dynamic classes on a scoped component.

That being said i'm not sure how to best solve the underlying issue of how to properly extract and preprocess svelte files within vite, that discussion is best continued in #54.

**Comment by Taha-Firoz** [comment]
> > whether this is the best or worst way to implement such a feature is a debate for another day.
Again I implemented this differently with a couple of selectors because that was easier to do, however it doesn't mean this problem should persist.


> would be better like this `<span class:bg-blue-500={foo} class:bg-blue-600={!foo}></span>` because it would be easier for an extractor to look for class:XXXX=  than to try and tokenize anything inside class={YYYYY}.

This wasn't working either tho, which is why I defaulted to adding it in the classes attribute.

**Comment by martinjeromelouis** [comment]
I don't have the second issue.
Regarding the first one, I have found the following workaround:

Instead of :
`<span class="{foo?"bg-blue-500":"bg-red-600"}"></span>`

use:
`<span class:blue-500-bg={foo} class:red-600-bg={!foo}></span>
<style>
.blue-500-bg {
  @apply bg-blue-500;
}

.red-600-bg {
  @apply bg-red-600;
}
</style>`

Another option is to use bg-$color where --color is a css variable. The value of the css variable can be conditionnally set in an inline css statement.

Of course, it would be better if windicss could handle the situation described above.

**Comment by Taha-Firoz** [comment]
That's fine if you have a couple of classes, but it gets very verbose if the number of classes you mean to add dynamically gets longer. I know there are a million better ways to do it, but when you're working quick and dirty you aren't usually thinking that hard
